# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themepreference',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='themepreference',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='arifare',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='hotel_cost',
        ),
        migrations.AddField(
            model_name='theme',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travelapp.Customer'),
        ),
        migrations.AddField(
            model_name='trip',
            name='airline',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='trip',
            name='depart_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='destination',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='origin',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='return_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='airfare_cost',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.DeleteModel(
            name='ThemePreference',
        ),
    ]
