# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_agent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trippreference',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Customer'),
        ),
    ]
